export {
  ensureMarkdownExtension,
  inspectMarkdownDocument,
  MARKDOWN_FILE_EXTENSIONS,
  openMarkdownDocument,
  saveMarkdownDocument,
  selectMarkdownFilePath,
  selectMarkdownSavePath,
  type MarkdownFileExtension,
  type MarkdownFileState,
  type OpenedMarkdownDocument,
  type SavedMarkdownDocument,
  type WriteMarkdownDocumentOptions,
} from "./services/markdownDocument";
export {
  MARKDOWN_DOCUMENT_CHANGED_EVENT,
  unwatchMarkdownDocument,
  watchMarkdownDocument,
  type MarkdownDocumentChangedEventPayload,
} from "./services/markdownDocumentApi";
export {
  formatUnrepresentableCharacters,
  getOpenMarkdownFileErrorMessage,
  getSaveMarkdownFileErrorMessage,
  isEncodingOpenError,
  isInspectMarkdownFileError,
  isOpenMarkdownFileError,
  isSaveMarkdownFileError,
  isUnrepresentableCharactersError,
  isWatchMarkdownDocumentError,
  type OpenMarkdownFileError,
  type SaveMarkdownFileError,
  type UnrepresentableCharactersError,
  type WatchMarkdownDocumentError,
} from "./utils/documentErrors";
export {
  ENCODING_CHOICES,
  formatDocumentEncoding,
  formatEncodingName,
  isSameEncoding,
  isUtf8Encoding,
  NEW_DOCUMENT_ENCODING,
  UTF8_ENCODING,
  UTF8_WITH_BOM_ENCODING,
  type DocumentEncoding,
  type EncodingChoice,
  type TextEncodingName,
} from "./utils/documentEncoding";
export { formatMarkdownForSave } from "./utils/documentSerialization";
export {
  getActiveDocumentKey,
  LINE_ENDINGS,
  matchesActiveDocumentKey,
  toSavedDocument,
  toUntitledDocument,
  type ActiveDocumentState,
  type ExternalFileChange,
  type FileMetadataSnapshot,
  type LineEnding,
  type SavedDocumentState,
  type UntitledDocumentState,
} from "./utils/documentState";
