// Milkdown-free for the same reason as ./contract, so command surfaces can label a command
// without loading the editor that runs it.
import type { EditorCommandId } from "./contract";

export const EDITOR_COMMAND_LABELS = {
  "edit.undo": "Undo",
  "edit.redo": "Redo",
  "edit.cut": "Cut",
  "edit.copy": "Copy",
  "edit.copyAsPlainText": "Plain text",
  "edit.copyAsMarkdown": "Markdown",
  "edit.paste": "Paste",
  "edit.pasteAsPlainText": "Plain text",
  "edit.pasteAsMarkdown": "Markdown",
  "edit.pasteAsRichText": "Rich text / formatted text",
  "edit.delete": "Delete",
  "edit.deleteWordBackward": "Delete word backward",
  "edit.deleteWordForward": "Delete word forward",
  "edit.selectAll": "Select all",
  "edit.selectWord": "Select word",
  "edit.jumpToTop": "Jump to top",
  "edit.jumpToBottom": "Jump to bottom",
  "edit.jumpToSelection": "Jump to selection",
  "edit.jumpToLineStart": "Jump to line start",
  "edit.jumpToLineEnd": "Jump to line end",
  "insert.paragraph": "Paragraph",
  "insert.heading1": "Heading 1",
  "insert.heading2": "Heading 2",
  "insert.heading3": "Heading 3",
  "insert.heading4": "Heading 4",
  "insert.heading5": "Heading 5",
  "insert.heading6": "Heading 6",
  "insert.link": "Link",
  "insert.image": "Image",
  "insert.orderedList": "Ordered list",
  "insert.unorderedList": "Unordered list",
  "insert.taskList": "Task list",
  "insert.blockquote": "Blockquote",
  "insert.codeBlock": "Code block",
  "insert.table": "Table",
  "insert.horizontalRule": "Horizontal rule",
  "format.strong": "Strong",
  "format.emphasis": "Emphasis",
  "format.strikethrough": "Strikethrough",
  "format.inlineCode": "Inline code",
  "format.clearInline": "Clear inline formatting",
  "format.paragraph": "Paragraph",
  "format.heading1": "Heading 1",
  "format.heading2": "Heading 2",
  "format.heading3": "Heading 3",
  "format.heading4": "Heading 4",
  "format.heading5": "Heading 5",
  "format.heading6": "Heading 6",
  "format.increaseHeading": "Increase heading level",
  "format.decreaseHeading": "Decrease heading level",
  "format.orderedList": "Ordered list",
  "format.unorderedList": "Unordered list",
  "format.taskList": "Task list",
  "format.increaseListIndent": "Increase list indent",
  "format.decreaseListIndent": "Decrease list indent",
  "format.toggleTaskChecked": "Toggle task checked",
  "format.blockquote": "Blockquote",
  "format.codeBlock": "Code block",
  "format.table.delete": "Delete table",
  "format.table.addRowAbove": "Add row above",
  "format.table.addRowBelow": "Add row below",
  "format.table.addColumnBefore": "Add column before",
  "format.table.addColumnAfter": "Add column after",
  "format.table.moveRowUp": "Move row up",
  "format.table.moveRowDown": "Move row down",
  "format.table.moveColumnLeft": "Move column left",
  "format.table.moveColumnRight": "Move column right",
  "format.table.deleteRow": "Delete row",
  "format.table.deleteColumn": "Delete column",
  "format.clearBlock": "Clear block formatting",
} satisfies Record<EditorCommandId, string>;
